name: Espresso full suite (manual)
on:
  workflow_dispatch:
  
  
jobs:
  visual_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: burrunan/gradle-cache-action@v1
        with:
          arguments: app:firebaseTestLabFullSuiteGrubhubStaging --scan
          gradle-version: wrapper
          gradle-build-scan-report: false
          gradle-distribution-sha-256-sum-warning: false
        env:
          STAGE_NAME: ${{github.job}}
          GH_ACTIONS_PACKAGE_KEY: ${{ secrets.GH_ACTIONS_PACKAGE_KEY }}

      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: '**/build/fladle/results/**/JUnitReport.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Setup NPM for reading xunit report
      - name: "Install dependencies"
        if: ${{ always() }}
        run: npm install xml-js @actions/glob @actions/core

      - name: "Prepare Slack message payload"
        uses: actions/github-script@v3
        if: ${{ always() }}
        id: set-result
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/slack_payload.js`)
            const { count, success, failed, skipped, annotations, slack } = await script({github, context, jobName: "${{github.job}}"})
            return slack
      - uses: wearerequired/slack-messaging-action@v1
        name: "Send Slack notification to #diner-android-e2e"
        if: ${{ always() }}
        with:
          bot_token: ${{ secrets.GH_ACTIONS_SLACK_BOT }}
          channel_id: C010GDTE9U4 # Id of #diner-android-e2e
          payload: >-
            ${{steps.set-result.outputs.result}}
